config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :departamentos do
    resources :municipios
  end
  resources :personas
  resources :barrio_colonia

  root 'static_pages#home'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'

  post 'barrio_colonia_list'  =>  'barrio_colonia#barrio_colonia_list', as: :barrio_colonia_list

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>Acerca del Registro de Votantes</h1>
<p>
	Esta es una aplicación web para el registro de votantes por departamento, municipio, macrosector, region, sector, barriocolonia. Necesita autorización para ingresar al sitio.
</p>

app/views/static_pages/contact.html.erb
<h1>Contáctanos</h1>
<p>
	En construcción
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenidos al Centro de Registro de Votantes</h1>

  <h2>
	Esta es la página de inicio para el registro de votantes
  </h2>

  <%= link_to "Departamentos", departamentos_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Municipios", "#", class: "btn btn-lg btn-primary" %>
  <%= link_to "Barrios y Colonias", barrio_colonia_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Personas", personas_path, class: "btn btn-lg btn-primary" %>
</div>