config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :departamentos do
    resources :municipios
  end
  resources :personas
  resources :barrio_colonia

  root 'static_pages#home'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'

  post 'barrio_colonia_list'  =>  'barrio_colonia#barrio_colonia_list', as: :barrio_colonia_list

end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
  belongs_to :departamento
  has_many :barrio_colonia
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  before_action :set_municipio, only: [:show, :edit, :update, :destroy]
  before_filter :get_departamento

  def get_departamento
    @departamento = Departamento.find(params[:departamento_id])
  end

  # GET /municipios
  # GET /municipios.json
  def index
    if params[:departamento_id]
      @municipios = @departamento.municipios
    else
      @municipios = Municipio.all
    end

    
  end

  # GET /municipios/1
  # GET /municipios/1.json
  def show
    @municipio = @departamento.municipios.find(params[:id])
  end

  # GET /municipios/new
  def new
    @municipio = Municipio.new
  end

  # GET /municipios/1/edit
  def edit
  end

  # POST /municipios
  # POST /municipios.json
  def create
    #@municipio = Municipio.new(municipio_params)
    @municipio = @departamento.municipios.new(municipio_params)

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to [@departamento, @municipio], notice: 'Municipio was successfully created.' }
        format.json { render :show, status: :created, location: [@departamento, @municipio] }
      else
        format.html { render :new }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipios/1
  # PATCH/PUT /municipios/1.json
  def update
    respond_to do |format|
      if @municipio.update(municipio_params)
        format.html { redirect_to @municipio, notice: 'Municipio was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipio }
      else
        format.html { render :edit }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio.destroy
    respond_to do |format|
      format.html { redirect_to municipios_url, notice: 'Municipio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipio
      @municipio = Municipio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipio_params
      params.require(:municipio).permit(:codigo_municipio, :nombre_municipio, :tipo_municipio, :departamento_id)
    end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/municipios/_form.html.erb
<%= form_for([@departamento, @municipio]) do |f| %>
  <% if @municipio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@municipio.errors.count, "error") %> prohibited this municipio from being saved:</h2>

      <ul>
      <% @municipio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo_municipio %><br>
    <%= f.number_field :codigo_municipio %>
  </div>
  <div class="field">
    <%= f.label :nombre_municipio %><br>
    <%= f.text_field :nombre_municipio %>
  </div>
  <div class="field">
    <%= f.label :departamento_id %><br>
    <%= f.collection_select  :departamento_id, Departamento.all, :id, :nombre_departamento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipios/edit.html.erb
<h1>Editing Municipio</h1>

<%= render 'form' %>

<%= link_to 'Show', [@departamento, @municipio] %> |
<%= link_to 'Back', departamento_municipios_path(@departamento) %>

app/views/municipios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Municipios</h1>

<table>
  <thead>
    <tr>
      <th>Codigo municipio</th>
      <th>Nombre municipio</th>
      <th>Departamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipios.each do |municipio| %>
      <tr>
        <td><%= municipio.codigo_municipio %></td>
        <td><%= municipio.nombre_municipio %></td>
        <td><%= municipio.departamento.nombre_departamento %></td>
        <td><%= link_to 'Show', departamento_municipios_path(@departamento) %></td>
        <td><%= link_to 'Edit', edit_departamento_municipio_path(@departamento, municipio) %></td>
        <td><%= link_to 'Destroy', departamento_municipios_path(@departamento), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipio', new_departamento_municipio_path(@departamento) %>

app/views/municipios/new.html.erb
<h1>New Municipio</h1>

<%= render 'form' %>

<%= link_to 'Back', departamento_municipios_path(@departamento) %>

app/views/municipios/show.html.erb
<p>
  <strong>Codigo municipio:</strong>
  <%= @municipio.codigo_municipio %>
</p>

<p>
  <strong>Nombre municipio:</strong>
  <%= @municipio.nombre_municipio %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @municipio.departamento %>
</p>

<%= link_to 'Edit', edit_departamento_municipio_path(@departamento, @municipio) %> |
<%= link_to 'Back', departamento_municipios_path(@departamento) %>