config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :departamentos do
    resources :municipios
  end
  resources :personas
  resources :barrio_colonia

  root 'static_pages#home'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'

  post 'barrio_colonia_list'  =>  'barrio_colonia#barrio_colonia_list', as: :barrio_colonia_list

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  belongs_to :barrio_colonium
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:identidad_persona, :nombres_persona, :apellidos_persona, :telefono_persona, :email_persona, :barrio_colonia_id)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identidad_persona %><br>
    <%= f.text_field :identidad_persona %>
  </div>
  <div class="field">
    <%= f.label :nombres_persona %><br>
    <%= f.text_field :nombres_persona %>
  </div>
  <div class="field">
    <%= f.label :apellidos_persona %><br>
    <%= f.text_field :apellidos_persona %>
  </div>
  <div class="field">
    <%= f.label :telefono_persona %><br>
    <%= f.text_field :telefono_persona %>
  </div>
  <div class="field">
    <%= f.label :email_persona %><br>
    <%= f.text_field :email_persona %>
  </div>
  <div class="field">
    <%= f.label :barrio_colonia_id %><br>
    <%= f.text_field :barrio_colonia_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personas</h1>

<table>
  <thead>
    <tr>
      <th>Identidad persona</th>
      <th>Nombres persona</th>
      <th>Apellidos persona</th>
      <th>Telefono persona</th>
      <th>Email persona</th>
      <th>Barrio colonia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.identidad_persona %></td>
        <td><%= persona.nombres_persona %></td>
        <td><%= persona.apellidos_persona %></td>
        <td><%= persona.telefono_persona %></td>
        <td><%= persona.email_persona %></td>
        <td><%= persona.barrio_colonia %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p>
  <strong>Identidad persona:</strong>
  <%= @persona.identidad_persona %>
</p>

<p>
  <strong>Nombres persona:</strong>
  <%= @persona.nombres_persona %>
</p>

<p>
  <strong>Apellidos persona:</strong>
  <%= @persona.apellidos_persona %>
</p>

<p>
  <strong>Telefono persona:</strong>
  <%= @persona.telefono_persona %>
</p>

<p>
  <strong>Email persona:</strong>
  <%= @persona.email_persona %>
</p>

<p>
  <strong>Barrio colonia:</strong>
  <%= @persona.barrio_colonia %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>